{"uuid": "ef65a964-2c06-4b1f-b5d7-210db26bb114", "children": ["27c8ca01-79de-4eb9-a6bf-888ccac89dfe", "b159f53e-eb12-4910-945b-9bd54b50fd7d"], "befores": [{"name": "setup_teardown", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Cannot verify the signature of 'C:\\Users\\syz\\AppData\\Local\\Temp\\202354-23592-12y2e5v.rcel\\appium-uiautomator2-server-v4.17.4.apk'. Original error: Exception in thread \"main\" java.lang.OutOfMemoryError\r\n\tat sun.misc.Unsafe.allocateMemory(Native Method)\r\n\tat java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:127)\r\n\tat java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:311)\r\n\tat com.android.apksig.internal.util.FileChannelDataSource.feed(FileChannelDataSource.java:102)\r\n\tat com.android.apksig.internal.zip.LocalFileRecord.outputUncompressedData(LocalFileRecord.java:384)\r\n\tat com.android.apksig.internal.zip.LocalFileRecord.outputUncompressedData(LocalFileRecord.java:434)\r\n\tat com.android.apksig.internal.apk.v1.V1SchemeVerifier.verifyJarEntriesAgainstManifestAndSigners(V1SchemeVerifier.java:1325)\r\n\tat com.android.apksig.internal.apk.v1.V1SchemeVerifier.access$700(V1SchemeVerifier.java:84)\r\n\tat com.android.apksig.internal.apk.v1.V1SchemeVerifier$Signers.verify(V1SchemeVerifier.java:363)\r\n\tat com.android.apksig.internal.apk.v1.V1SchemeVerifier$Signers.access$100(V1SchemeVerifier.java:204)\r\n\tat com.android.apksig.internal.apk.v1.V1SchemeVerifier.verify(V1SchemeVerifier.java:126)\r\n\tat com.android.apksig.ApkVerifier.verify(ApkVerifier.java:294)\r\n\tat com.android.apksig.ApkVerifier.verify(ApkVerifier.java:149)\r\n\tat com.android.apksigner.ApkSignerTool.verify(ApkSignerTool.java:531)\r\n\tat com.android.apksigner.ApkSignerTool.main(ApkSignerTool.java:91)\r\n\nStacktrace:\nUnknownError: An unknown server-side error occurred while processing the command. Original error: Cannot verify the signature of 'C:\\Users\\syz\\AppData\\Local\\Temp\\202354-23592-12y2e5v.rcel\\appium-uiautomator2-server-v4.17.4.apk'. Original error: Exception in thread \"main\" java.lang.OutOfMemoryError\r\n\tat sun.misc.Unsafe.allocateMemory(Native Method)\r\n\tat java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:127)\r\n\tat java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:311)\r\n\tat com.android.apksig.internal.util.FileChannelDataSource.feed(FileChannelDataSource.java:102)\r\n\tat com.android.apksig.internal.zip.LocalFileRecord.outputUncompressedData(LocalFileRecord.java:384)\r\n\tat com.android.apksig.internal.zip.LocalFileRecord.outputUncompressedData(LocalFileRecord.java:434)\r\n\tat com.android.apksig.internal.apk.v1.V1SchemeVerifier.verifyJarEntriesAgainstManifestAndSigners(V1SchemeVerifier.java:1325)\r\n\tat com.android.apksig.internal.apk.v1.V1SchemeVerifier.access$700(V1SchemeVerifier.java:84)\r\n\tat com.android.apksig.internal.apk.v1.V1SchemeVerifier$Signers.verify(V1SchemeVerifier.java:363)\r\n\tat com.android.apksig.internal.apk.v1.V1SchemeVerifier$Signers.access$100(V1SchemeVerifier.java:204)\r\n\tat com.android.apksig.internal.apk.v1.V1SchemeVerifier.verify(V1SchemeVerifier.java:126)\r\n\tat com.android.apksig.ApkVerifier.verify(ApkVerifier.java:294)\r\n\tat com.android.apksig.ApkVerifier.verify(ApkVerifier.java:149)\r\n\tat com.android.apksigner.ApkSignerTool.verify(ApkSignerTool.java:531)\r\n\tat com.android.apksigner.ApkSignerTool.main(ApkSignerTool.java:91)\r\n\n    at getResponseForW3CError (C:\\Program Files\\Appium\\resources\\app\\node_modules\\appium\\node_modules\\appium-base-driver\\lib\\protocol\\errors.js:804:9)\n    at asyncHandler (C:\\Program Files\\Appium\\resources\\app\\node_modules\\appium\\node_modules\\appium-base-driver\\lib\\protocol\\protocol.js:380:37)\n", "trace": "  File \"C:\\Users\\syz\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\syz\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\_pytest\\fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\syz\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\_pytest\\fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\python_Code\\pythonProject\\pythonclasses\\autoclass\\day07\\appautotest\\conftest.py\", line 28, in setup_teardown\n    driver = webdriver.Remote(\"http://127.0.0.1:4723/wd/hub\", Caps.caps_for_xiaomishop)\n  File \"C:\\Users\\syz\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 275, in __init__\n    AppiumConnection(command_executor, keep_alive=keep_alive), desired_capabilities, browser_profile, proxy\n  File \"C:\\Users\\syz\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 269, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"C:\\Users\\syz\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 369, in start_session\n    response = self.execute(RemoteCommand.NEW_SESSION, parameters)\n  File \"C:\\Users\\syz\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 425, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\syz\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 247, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1685855982277, "stop": 1685856012331}], "start": 1685855982277, "stop": 1685856012480}